### ISSUE TITLE
keine Werte

### ISSUE THREAD

**Issue by totocotonio** [klein0r/ioBroker.luftdaten#62] opened 2022-01-10 17:18 UTC
### The problem

Seit update auf 2.1.1 kommen keine Daten mehr rein

### Version of nodejs

14.17.6

### Version of ioBroker js-controller

5.2.3

### Version of Adapter

2.1..1

### Operating system running ioBroker

linux

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

### Additional information & file uploads

getaddrinfo EAI_AGAIN luftdaten

sonst kein Fehler im Log

**Comment by klein0r** [comment] 2022-01-10 17:47
Zeig mal bitte deine Konfiguration

**Comment by totocotonio** [comment] 2022-01-10 19:14
![luftdaten](https://user-images.githubusercontent.com/48123111/148825262-9c2633dd-9c79-47f7-97f8-d5e4cc67c957.png)

**Comment by klein0r** [comment] 2022-01-10 19:59
Duplicate of #61 

https://github.com/klein0r/ioBroker.luftdaten/blob/master/docs/de/basics.md

**Closed by klein0r** 2022-01-10 19:59 UTC
Labels: bug
